name: New version check
on:
  workflow_dispatch:
  schedule:
  - cron: 0 16 * * 5
  push:
    branches:
      - master

jobs:
  check:
    name: Check new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: showwin/speedtest-go
          BRANCH: master
          SOURCE_URL: https://github.com/showwin/speedtest-go/archive/refs/tags/{{version}}.tar.gz
          
